In [11]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

# 2.1. Numpy ndarray - создание

Numpy - библиотека для векторизованных вычислений в Python'e. Написана на C. Основной объект в numpy - nddarray, который располагается напрерывно в памяти и позволяет производить быстрые вычисления.

Создание массива

In [12]:
a = np.array([1, 2, 3, 4])

In [13]:
a

array([1, 2, 3, 4])

In [14]:
a.shape

(4,)

Shape - кортеж, который указывает число элементов в каждом измерении. 

In [29]:
a = np.array([[[1, 2], [3, 4]], 
             [[12, 23], [34, 4]],
              [[2, 21], [54, 44]] ])

In [16]:
a.shape

(3, 2, 2)

In [17]:
a

array([[[ 1,  2],
        [ 3,  4]],

       [[12, 23],
        [34,  4]],

       [[ 2, 21],
        [54, 44]]])

In [18]:
a.T

array([[[ 1, 12,  2],
        [ 3, 34, 54]],

       [[ 2, 23, 21],
        [ 4,  4, 44]]])

In [19]:
a = np.array([1, 2, 3])

In [20]:
a

array([1, 2, 3])

In [25]:
np.arange(0, 10, 3)

array([0, 3, 6, 9])

In [26]:
np.arange(start=10, stop=-3, step=-2)

array([10,  8,  6,  4,  2,  0, -2])

In [27]:
a

array([1, 2, 3])

In [28]:
a.shape

(3,)

In [30]:
a

array([[[ 1,  2],
        [ 3,  4]],

       [[12, 23],
        [34,  4]],

       [[ 2, 21],
        [54, 44]]])

In [31]:
a.reshape(2, 2, 3)

array([[[ 1,  2,  3],
        [ 4, 12, 23]],

       [[34,  4,  2],
        [21, 54, 44]]])

In [ ]:
a.shape

In [32]:
a.dtype

dtype('int64')

In [33]:
a.itemsize

8

In [34]:
a.nbytes

96

In [35]:
a

array([[[ 1,  2],
        [ 3,  4]],

       [[12, 23],
        [34,  4]],

       [[ 2, 21],
        [54, 44]]])

In [39]:
a.reshape(2, 1, -1)

array([[[ 1,  2,  3,  4, 12, 23]],

       [[34,  4,  2, 21, 54, 44]]])

In [41]:
a.reshape(-1, 3)

array([[ 1,  2,  3],
       [ 4, 12, 23],
       [34,  4,  2],
       [21, 54, 44]])

In [42]:
a.reshape(4, -1)

array([[ 1,  2,  3],
       [ 4, 12, 23],
       [34,  4,  2],
       [21, 54, 44]])

In [43]:
a.reshape(2, -1)

array([[ 1,  2,  3,  4, 12, 23],
       [34,  4,  2, 21, 54, 44]])

In [44]:
a.reshape(1, -1)

array([[ 1,  2,  3,  4, 12, 23, 34,  4,  2, 21, 54, 44]])

In [45]:
a.reshape(1, -1).shape

(1, 12)

In [46]:
a.reshape(-1, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [12],
       [23],
       [34],
       [ 4],
       [ 2],
       [21],
       [54],
       [44]])

При желании, можно использовать np.size(np.object) и np.shape(np.object):

In [47]:
np.size(a)

12

In [48]:
np.shape(a)

(3, 2, 2)

In [49]:
a.size

12

In [50]:
a.shape

(3, 2, 2)

При необходимости, не стоит принебрегать встроенной справкой:

Shift + tab*(1, 2, 4)

In [54]:
np.array([1, 12., "sa"], dtype="O")

array([1, 12.0, 'sa'], dtype=object)

И специальными функциями numpy:

In [55]:
a

array([[[ 1,  2],
        [ 3,  4]],

       [[12, 23],
        [34,  4]],

       [[ 2, 21],
        [54, 44]]])

In [58]:
np.zeros((5, 5)).astype(int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [59]:
np.zeros_like(a)

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [60]:
np.lookfor('create array of zeros')

Search results for 'create array of zeros'
------------------------------------------
numpy.zeros_like
    Return an array of zeros with the same shape and type as a given array.
numpy.array
    Create an array.
numpy.ndarray
    ndarray(shape, dtype=float, buffer=None, offset=0,
numpy.ones_like
    Return an array of ones with the same shape and type as a given array.
numpy.diag_indices
    Return the indices to access the main diagonal of an array.
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.pad
    Pad an array.
numpy.nditer
    Efficient multi-dimensional iterator object to iterate over arrays.
numpy.full_like
    Return a full array with the same shape and type as a given array.
numpy.empty_like
    Return a new array with the same shape and type as a given array.
numpy.left_shift
    Shift the bits of an integer to the left.
numpy.fft.ifft
    Compute the one-dimensional inverse discrete Fourier Transform.
numpy.fft.ifftn
    Compute the N-dimensional invers

и IPython:

In [61]:
np.ar*?

In [62]:
a = np.array([[1, 2], [3, 4]])

In [63]:
a[0, 0] = 100

In [64]:
a

array([[100,   2],
       [  3,   4]])

In [65]:
a = (1, 2)

In [67]:
a = (100, 2)

**Создание массивов**

Создавать из списков мы уже умеем:

In [68]:
x = [1, 2, 3, 4]

In [69]:
np.array([1, 2, 3, 4], dtype=str)

array(['1', '2', '3', '4'], dtype='<U1')

In [70]:
np.arange(100, 1000, 30)

array([100, 130, 160, 190, 220, 250, 280, 310, 340, 370, 400, 430, 460,
       490, 520, 550, 580, 610, 640, 670, 700, 730, 760, 790, 820, 850,
       880, 910, 940, 970])

In [78]:
np.linspace(0, 1, 26)

array([0.  , 0.04, 0.08, 0.12, 0.16, 0.2 , 0.24, 0.28, 0.32, 0.36, 0.4 ,
       0.44, 0.48, 0.52, 0.56, 0.6 , 0.64, 0.68, 0.72, 0.76, 0.8 , 0.84,
       0.88, 0.92, 0.96, 1.  ])

In [76]:
np.linspace(0, 1, 25, endpoint=False)

array([0.  , 0.04, 0.08, 0.12, 0.16, 0.2 , 0.24, 0.28, 0.32, 0.36, 0.4 ,
       0.44, 0.48, 0.52, 0.56, 0.6 , 0.64, 0.68, 0.72, 0.76, 0.8 , 0.84,
       0.88, 0.92, 0.96])

In [ ]:
np.linspace(0, 1, 26)

In [79]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [80]:
np.ones(3)

array([1., 1., 1.])

In [81]:
np.zeros((3, 2, 4, 5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [82]:
A = np.arange(100).reshape(4, 25)

In [83]:
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [84]:
np.ones_like(A)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1]])

In [85]:
np.zeros_like(A)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0]])

In [86]:
np.diag(np.array([1, 2, 3, 4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

** Случайные массивы **

на интервале [0,1]:

In [87]:
np.random.rand(3, 2)

array([[0.50755507, 0.0211933 ],
       [0.43352176, 0.44631306],
       [0.23881999, 0.83024573]])

Нормально распределенные:

In [88]:
np.random.randn(3, 2)

array([[ 0.53942869,  1.52676162],
       [-3.2771929 , -1.84856065],
       [ 0.67212494, -1.49297925]])

-- N: иногда полезно получить случайное целое число:

In [89]:
np.random.randint(0, 100, (3, 4))

array([[68, 83, 20, 65],
       [56, 54, 40,  7],
       [17, 79, 43, 45]])

In [90]:
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

# 2.2. Numpy ndarray - индексы

Отдельно рассмотрим 1-мерный и многомерные массивы.

In [91]:
t = np.random.rand(3,)

In [92]:
t

array([0.01220009, 0.45699848, 0.93175194])

Для одномерного массива получим сразу элемент, который находится по данному индексу. Для n-мерного массива подобная индексация вернет массив размера n-1.

In [93]:
t.shape

(3,)

In [99]:
t[2]

0.9317519418549508

In [100]:
t = np.random.rand(3, 5, 10)
t

array([[[0.84602469, 0.47332988, 0.90255503, 0.22599553, 0.30415374,
         0.71499388, 0.72409148, 0.01867644, 0.2858131 , 0.58048634],
        [0.93078663, 0.3389969 , 0.12008312, 0.51627271, 0.69920706,
         0.29864068, 0.86160962, 0.9058072 , 0.76858325, 0.26123164],
        [0.9384556 , 0.93864246, 0.74504455, 0.91073504, 0.23722471,
         0.49496735, 0.80987834, 0.95456578, 0.63748325, 0.91084975],
        [0.69213675, 0.04294299, 0.8335869 , 0.36994852, 0.936557  ,
         0.48305288, 0.12533161, 0.96445418, 0.01702583, 0.67657077],
        [0.14043997, 0.15531285, 0.64955775, 0.98165422, 0.69480742,
         0.76197389, 0.42520918, 0.13889344, 0.2161863 , 0.76470027]],

       [[0.05460587, 0.49012299, 0.18069018, 0.63092485, 0.55124203,
         0.56708121, 0.81834498, 0.9389873 , 0.19290141, 0.71284402],
        [0.6979398 , 0.2582965 , 0.91580782, 0.53235819, 0.55796442,
         0.32277227, 0.33863078, 0.33230155, 0.97881821, 0.2032152 ],
        [0.66702606, 0.57

In [101]:
t.shape

(3, 5, 10)

In [102]:
t[0, 1, :]

array([0.93078663, 0.3389969 , 0.12008312, 0.51627271, 0.69920706,
       0.29864068, 0.86160962, 0.9058072 , 0.76858325, 0.26123164])

In [103]:
t[0, 1, 5]

0.2986406770764749

In [104]:
t[1][0].shape

(10,)

In [105]:
np.random.rand(3, 5)[1].shape

(5,)

Можно использовать ':' вместо индекса:

In [122]:
A = np.random.rand(3, 5)

In [123]:
A

array([[0.02872195, 0.90212882, 0.23654588, 0.12858426, 0.31787579],
       [0.8487613 , 0.83229775, 0.34565135, 0.23997119, 0.53578755],
       [0.27146694, 0.03443087, 0.62708559, 0.52020046, 0.04195581]])

In [108]:
A[:, 2]

array([0.88698963, 0.39499287, 0.76803089])

In [109]:
A[0, :]

array([0.05213634, 0.09272932, 0.88698963, 0.16815097, 0.36288661])

In [110]:
A[:, 0]

array([0.05213634, 0.65428189, 0.42895903])

Поддерживается стандартный протокол - python slicing syntax ([lower:upper:step]) :

In [111]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [112]:
A = np.arange(10)

In [113]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
A[0:10:2]

array([0, 2, 4, 6, 8])

In [115]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
a = A[0, :]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [ ]:
a

Операция slicing создает т.н. view - то есть данные не копируются, поэтому исходный объект по адресу - mutable.

In [117]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
A[0:5:2] = 0

In [119]:
A

array([0, 1, 0, 3, 0, 5, 6, 7, 8, 9])

Параметры для slicing могут пропускаться:

In [ ]:
A

In [127]:
A[0, :][0:4:2]

array([0.02872195, 0.23654588])

In [125]:
A[0, :][0:4:]

array([0.02872195, 0.90212882, 0.23654588, 0.12858426])

In [128]:
A[0, :][0:3]

array([0.02872195, 0.90212882, 0.23654588])

In [129]:
A[0, :][2:5]

array([0.23654588, 0.12858426, 0.31787579])

In [130]:
A[0, :]

array([0.02872195, 0.90212882, 0.23654588, 0.12858426, 0.31787579])

In [132]:
A

array([[0.02872195, 0.90212882, 0.23654588, 0.12858426, 0.31787579],
       [0.8487613 , 0.83229775, 0.34565135, 0.23997119, 0.53578755],
       [0.27146694, 0.03443087, 0.62708559, 0.52020046, 0.04195581]])

In [134]:
A[::-1, :]

array([[0.27146694, 0.03443087, 0.62708559, 0.52020046, 0.04195581],
       [0.8487613 , 0.83229775, 0.34565135, 0.23997119, 0.53578755],
       [0.02872195, 0.90212882, 0.23654588, 0.12858426, 0.31787579]])

In [135]:
A[:, ::-1]

array([[0.31787579, 0.12858426, 0.23654588, 0.90212882, 0.02872195],
       [0.53578755, 0.23997119, 0.34565135, 0.83229775, 0.8487613 ],
       [0.04195581, 0.52020046, 0.62708559, 0.03443087, 0.27146694]])

In [133]:
A[::-1, ::-1]

array([[0.04195581, 0.52020046, 0.62708559, 0.03443087, 0.27146694],
       [0.53578755, 0.23997119, 0.34565135, 0.83229775, 0.8487613 ],
       [0.31787579, 0.12858426, 0.23654588, 0.90212882, 0.02872195]])

In [136]:
A[0, :]

array([0.02872195, 0.90212882, 0.23654588, 0.12858426, 0.31787579])

In [137]:
A[0, :][:-3]

array([0.02872195, 0.90212882])

In [138]:
A[0, :][-3:]

array([0.23654588, 0.12858426, 0.31787579])

** Fancy Indexing **

Этим термином обозначается индексирование с помощью массивов (или иных итерируемых конструкций).

In [139]:
A

array([[0.02872195, 0.90212882, 0.23654588, 0.12858426, 0.31787579],
       [0.8487613 , 0.83229775, 0.34565135, 0.23997119, 0.53578755],
       [0.27146694, 0.03443087, 0.62708559, 0.52020046, 0.04195581]])

In [142]:
row_indices = [1, 2]
A[[1, 2]]

array([[0.8487613 , 0.83229775, 0.34565135, 0.23997119, 0.53578755],
       [0.27146694, 0.03443087, 0.62708559, 0.52020046, 0.04195581]])

In [143]:
col_indices = [1, -1] # [1, 4]
A[row_indices, col_indices]

array([0.83229775, 0.04195581])

Возможно Булево индексирование (**Boolean indexing**):

In [145]:
B

array([ 0,  1,  4,  9, 16])

In [151]:
B = np.array([n for n in range(5)]) ** 2
row_mask = np.array([True, False, True, False, False])
B[row_mask]

array([0, 4])

In [146]:
B

array([ 0,  1,  4,  9, 16])

In [147]:
B[B > 2]

array([ 4,  9, 16])

In [148]:
B[(B <= 0) | (B > 2)]

array([ 0,  4,  9, 16])

In [152]:
np.array([1, 0, 1, 0, 0], dtype=bool)

array([ True, False,  True, False, False])

In [153]:
row_mask = np.array([1, 0, 1, 0, 0], dtype=bool)
B[row_mask]

array([0, 4])

In [154]:
row_mask

array([ True, False,  True, False, False])

In [155]:
B

array([ 0,  1,  4,  9, 16])

In [156]:
row_mask = np.array([1, 0, 1, 0, 3])
B[row_mask]

array([1, 0, 1, 0, 9])

Это очень удобно, как вы наверняка догадались, если мы хотим отобрать данные, отвечающие определенным условиям:

In [157]:
x = np.arange(0, 10, 0.5)
x

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [161]:
mask = (5 <= x) * (x <= 7.5)
mask

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True, False, False,
       False, False])

In [164]:
mask = (5 <= x) & (x <= 7.5)
mask

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True, False, False,
       False, False])

In [165]:
x[mask]

array([5. , 5.5, 6. , 6.5, 7. , 7.5])

In [166]:
a = np.array([[1, 2], [3, 4], [4, 5]])

In [167]:
a

array([[1, 2],
       [3, 4],
       [4, 5]])

In [168]:
(a > 1)

array([[False,  True],
       [ True,  True],
       [ True,  True]])

In [169]:

a > 2

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [170]:
a[a > 2]

array([3, 4, 4, 5])

Получить список индексов элементов, отвечающих заданной маске, можно с помощью **where**:

In [171]:
mask

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True, False, False,
       False, False])

In [172]:
indices = np.where(mask == True)

indices

(array([10, 11, 12, 13, 14, 15]),)

In [173]:
A

array([[0.02872195, 0.90212882, 0.23654588, 0.12858426, 0.31787579],
       [0.8487613 , 0.83229775, 0.34565135, 0.23997119, 0.53578755],
       [0.27146694, 0.03443087, 0.62708559, 0.52020046, 0.04195581]])

In [174]:
A[(A < 1) | (A > 2)]

array([0.02872195, 0.90212882, 0.23654588, 0.12858426, 0.31787579,
       0.8487613 , 0.83229775, 0.34565135, 0.23997119, 0.53578755,
       0.27146694, 0.03443087, 0.62708559, 0.52020046, 0.04195581])

In [175]:
mask

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True, False, False,
       False, False])

In [176]:
x[np.where(mask == True)]

array([5. , 5.5, 6. , 6.5, 7. , 7.5])

## TLDR:
* для доступа к элементам массива пользуйтесь slicing и помните, что slicing создает view, а значит исходный массив может быть изменен.

# 2.3. Numpy ndarray - элементарные операции с массивами

** Broadcasting **

Концепеция broadcasting является ключевой для понимания операций с массивами. Обычно, операции с массивами производятся поэлементно. 

In [192]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])

In [178]:
a / b

array([0.5, 1. , 1.5])

Что, если массивы разного размера? Начнем с простого - скаляр и вектор:

In [179]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])

In [180]:
a * np.array([2., 2., 2.])

array([2., 4., 6.])

** Операции вида "массив - скаляр" **

In [181]:
A * 2

array([[0.05744391, 1.80425763, 0.47309176, 0.25716852, 0.63575158],
       [1.69752259, 1.66459549, 0.6913027 , 0.47994238, 1.07157511],
       [0.54293387, 0.06886175, 1.25417118, 1.04040092, 0.08391163]])

In [182]:
np.eye(3) * 2

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

In [183]:
np.ones_like(A) * 2

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [184]:
A + np.ones_like(A) * 2

array([[2.02872195, 2.90212882, 2.23654588, 2.12858426, 2.31787579],
       [2.8487613 , 2.83229775, 2.34565135, 2.23997119, 2.53578755],
       [2.27146694, 2.03443087, 2.62708559, 2.52020046, 2.04195581]])

In [185]:
A + 2

array([[2.02872195, 2.90212882, 2.23654588, 2.12858426, 2.31787579],
       [2.8487613 , 2.83229775, 2.34565135, 2.23997119, 2.53578755],
       [2.27146694, 2.03443087, 2.62708559, 2.52020046, 2.04195581]])

** Операции вида "массив - массив" **

Производятся поэлементно с учетом правил broadcasting:

In [186]:
A * A

array([[0.00082495, 0.8138364 , 0.05595395, 0.01653391, 0.10104502],
       [0.72039574, 0.69271954, 0.11947486, 0.05758617, 0.2870683 ],
       [0.0736943 , 0.00118549, 0.39323634, 0.27060852, 0.00176029]])

In [187]:
A / A

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

** Матричные операции**

In [188]:
A = np.random.rand(3, 3)

In [189]:
A

array([[0.75747277, 0.98834976, 0.80140096],
       [0.34398109, 0.33539124, 0.3515714 ],
       [0.44294568, 0.57949344, 0.61756091]])

In [190]:
A.shape

(3, 3)

In [193]:
b.reshape(3, 1).shape

(3, 1)

In [194]:
np.dot(A, b.reshape(3, 1))

array([[5.09444698],
       [2.06188746],
       [3.28000005]])

In [195]:
A.dot(A)

array([[1.26871571, 1.54453848, 1.44942882],
       [0.53165158, 0.65619423, 0.6106975 ],
       [0.80840001, 0.99001477, 0.94009189]])

In [196]:
np.dot(A, A)

array([[1.26871571, 1.54453848, 1.44942882],
       [0.53165158, 0.65619423, 0.6106975 ],
       [0.80840001, 0.99001477, 0.94009189]])

In [197]:
A = np.arange(9).reshape(-3, 3)

In [198]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Если хочется использовать по умолчанию операции из матричной алгебры, то можно использовать конструктор matrix().

In [199]:
M = np.matrix(A)

In [200]:
M

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [202]:
v = b

In [203]:
v1 = np.matrix(v).T

In [204]:
M.shape

(3, 3)

In [205]:
v1

matrix([[2.],
        [2.],
        [2.]])

In [206]:
v1.T * v1

matrix([[12.]])

In [207]:
M * v1

matrix([[ 6.],
        [24.],
        [42.]])

** Преобразование массивов**

In [208]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [209]:
A.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

** reshape **

In [210]:
a = np.array([1, 2, 3, 4])

In [211]:
a = a.reshape((2, 2))

In [212]:
a

array([[1, 2],
       [3, 4]])

In [213]:
a.reshape(-1, 2)

array([[1, 2],
       [3, 4]])

** concatenate **

In [214]:
a = np.array([[1, 3]])

In [215]:
b = np.array([[5, 6]])

In [216]:
a

array([[1, 3]])

In [217]:
b

array([[5, 6]])

In [218]:
np.concatenate((a, b))

array([[1, 3],
       [5, 6]])

In [219]:
b

array([[5, 6]])

In [220]:
b.T

array([[5],
       [6]])

In [221]:
a

array([[1, 3]])

In [222]:
b

array([[5, 6]])

In [223]:
np.concatenate((a, b), axis=0)

array([[1, 3],
       [5, 6]])

In [224]:
np.concatenate((a, b), axis=1)

array([[1, 3, 5, 6]])

** hstack **

Название говорит само за себя - horizontal stack.

In [225]:
a = np.array([[1], [3]])

In [226]:
a

array([[1],
       [3]])

In [227]:
b.T

array([[5],
       [6]])

In [228]:
np.hstack((a, b.T))

array([[1, 5],
       [3, 6]])

In [229]:
a.shape

(2, 1)

In [230]:
b.T.shape

(2, 1)

** vstack **

In [231]:
a = np.array([2, 3])
b = np.array([4, 5])

In [232]:
np.vstack((a, b))

array([[2, 3],
       [4, 5]])

In [233]:
np.hstack((a, b))

array([2, 3, 4, 5])

In [ ]:
a.shape

In [ ]:
b.shape

** Копии и view **

Мы помним, что очень важно различать копирование объекта и присваивание новой ссылки на объект. Numpy в этом смысле не отличается от списков:

In [234]:
A = np.array([[1, 2], [3, 4]])

In [235]:
A

array([[1, 2],
       [3, 4]])

In [236]:
B = A

In [238]:
B[0, 0] = 10

In [239]:
A

array([[10,  2],
       [ 3,  4]])

Если это не тот тип поведения, который нам нужен - следует использовать np.copy():

In [240]:
A = np.array([[1, 2], [3, 4]])

In [241]:
B = np.copy(A)

In [242]:
B[0, 0] = 100

In [243]:
B

array([[100,   2],
       [  3,   4]])

In [244]:
A

array([[1, 2],
       [3, 4]])

Важно помнить, что если вы используете view массива, то копии вы не создаете!

In [245]:
a = np.arange(10)

In [246]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [247]:
b = a[::2]

In [248]:
b

array([0, 2, 4, 6, 8])

In [249]:
np.may_share_memory(a, b)

True

In [250]:
c = a[::2].copy()
np.may_share_memory(a, c)

False

In [251]:
d = np.copy(a.T)
np.may_share_memory(a, d)

False

In [ ]:
d[2] = 1000

In [ ]:
a

In [ ]:
b[0] = -11

In [ ]:
a

## TLDR:
* следует отличать копию массива и view;
* при осуществлении операций помните про правила broadcasting;
* запомните hstack и vstack.

# 2.4. Numpy - основные функции.

** Встроенные функции массива **

In [252]:
m = np.random.randint(0, 10, (3, 3))

In [254]:
m

array([[2, 2, 2],
       [1, 5, 9],
       [5, 3, 7]])

In [255]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [256]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [257]:
m * np.eye(3)

array([[2., 0., 0.],
       [0., 5., 0.],
       [0., 0., 7.]])

In [258]:
np.diag(m[np.eye(3, dtype="bool")])

array([[2, 0, 0],
       [0, 5, 0],
       [0, 0, 7]])

In [ ]:
m[np.eye(3, dtype=bool)].sum()

In [259]:
np.max(m)

9

In [264]:
m

array([[2, 2, 2],
       [1, 5, 9],
       [5, 3, 7]])

In [265]:
m.max(axis=0)

array([5, 5, 9])

In [263]:
m.min(axis=1)

array([2, 1, 3])

** Всегда используйте встроенные функции! **

In [266]:
a = np.random.rand(1000)

In [267]:
%timeit -n 1000 max(a)

90.6 µs ± 1.14 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [268]:
%timeit -n 1000 a.max()

3.44 µs ± 806 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [270]:
%timeit -n 1000 sum(a)

152 µs ± 768 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [271]:
%timeit -n 1000 a.sum()

3.4 µs ± 1.08 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [272]:
%timeit -n 1000 np.sum(a)

6.23 µs ± 399 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Просто считать сумму элементов матрицы или находить максимальный элемент не так интересно, и тут нам помогают axis:

In [273]:
np.sum(m)

36

In [274]:
m.sum(axis=0)

array([ 8, 10, 18])

In [275]:
m.sum(axis=1)

array([ 6, 15, 15])

In [276]:
m.max(axis=0)

array([5, 5, 9])

Очень полезно произведение всех элементов:

In [277]:
m

array([[2, 2, 2],
       [1, 5, 9],
       [5, 3, 7]])

In [279]:
m.prod()

37800

In [280]:
m

array([[2, 2, 2],
       [1, 5, 9],
       [5, 3, 7]])

In [281]:
np.hstack((m, m))

array([[2, 2, 2, 2, 2, 2],
       [1, 5, 9, 1, 5, 9],
       [5, 3, 7, 5, 3, 7]])

In [282]:
np.concatenate((m, m), axis=1)

array([[2, 2, 2, 2, 2, 2],
       [1, 5, 9, 1, 5, 9],
       [5, 3, 7, 5, 3, 7]])

In [283]:
m.prod()

37800

**Простые статистики**

**Среднее**

In [284]:
m

array([[2, 2, 2],
       [1, 5, 9],
       [5, 3, 7]])

In [285]:
m.mean(axis=0)

array([2.66666667, 3.33333333, 6.        ])

In [286]:
np.mean(m, axis=1)

array([2., 5., 5.])

In [287]:
np.mean(m)

4.0

In [288]:
m.mean(axis=0)

array([2.66666667, 3.33333333, 6.        ])

**Медиана**

In [289]:
np.median(m, axis=0)

array([2., 3., 7.])

In [290]:
np.median(m)

3.0

** Дисперсия **

In [291]:
np.std(m, axis=0)

array([1.69967317, 1.24721913, 2.94392029])

In [292]:
m.std(axis=0)

array([1.69967317, 1.24721913, 2.94392029])

In [293]:
np.var(m)

6.444444444444445

In [294]:
m.var()

6.444444444444445

** Сортировка **

In [295]:
a = np.random.randint(0, 100, 12)

In [296]:
a

array([49, 66, 17, 79, 65, 88, 80, 97, 61, 79, 83, 95])

In [297]:
sorted(a, reverse=True)

[97, 95, 88, 83, 80, 79, 79, 66, 65, 61, 49, 17]

In [298]:
a

array([49, 66, 17, 79, 65, 88, 80, 97, 61, 79, 83, 95])

In [299]:
np.sort(a)[::-1]

array([97, 95, 88, 83, 80, 79, 79, 66, 65, 61, 49, 17])

Функция выше возвращает отсортированную копию массива. Если нужна сортировка in-place:

In [304]:
a = np.random.randint(0, 100, 12)

In [305]:
np.sort(a)

array([10, 30, 42, 43, 46, 47, 50, 74, 74, 75, 91, 96])

In [306]:
a

array([30, 74, 10, 74, 46, 42, 96, 91, 50, 47, 43, 75])

In [302]:
a = np.sort(a)

In [303]:
a

array([ 4, 18, 20, 45, 54, 55, 61, 62, 70, 74, 94, 95])

In [312]:
a = np.random.randint(0, 100, 12)

In [313]:
a

array([77, 17, 94,  2, 88,  0,  7, 84, 78, 92, 43, 10])

In [315]:
a = np.sort(a)

In [316]:
a

array([ 0,  2,  7, 10, 17, 43, 77, 78, 84, 88, 92, 94])

In [317]:
a.sort()

In [311]:
a

In [ ]:
a = np.random.rand(100)

In [ ]:
a = np.random.randint(0, 100, 120)

In [ ]:
a

Также иногда бывает полезно получить только список индексов в правильном порядке:

In [318]:
a = np.random.randint(0, 10, 10)

In [319]:
a

array([9, 4, 8, 0, 1, 6, 5, 5, 0, 8])

In [322]:
np.argsort(a)

array([3, 8, 4, 1, 6, 7, 5, 2, 9, 0])

In [321]:
a[np.argsort(a)]

array([0, 0, 1, 4, 5, 5, 6, 8, 8, 9])

In [ ]:
a[np.argsort(a)]

In [323]:
np.argmax(a)

0

In [324]:
np.argmin(a)

3

In [325]:
a

array([9, 4, 8, 0, 1, 6, 5, 5, 0, 8])

In [326]:
a

array([9, 4, 8, 0, 1, 6, 5, 5, 0, 8])

In [327]:
np.nonzero(a)

(array([0, 1, 2, 4, 5, 6, 7, 9]),)

** Функции для работы с матрицами **

In [328]:
m

array([[2, 2, 2],
       [1, 5, 9],
       [5, 3, 7]])

In [329]:
np.diag(m)

array([2, 5, 7])

In [330]:
m.diagonal()

array([2, 5, 7])

Для целого класса функций из линейной алгебры есть свой суб-модуль np.linalg.

http://docs.scipy.org/doc/numpy/reference/routines.linalg.html

** Условные выражения **

Как вы уже поняли, для вектора конструкция типа if (vector) не подходит.

In [331]:
M

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [332]:
(M > 0)

matrix([[False,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])

In [334]:
i = 0
if (M >= i).all():
    print("at least one element in M is larger than {}".format(i))
else:
    print("no element in M is larger than {}".format(i))

at least one element in M is larger than 0


In [335]:
if (M > -1).all():
    print("all elements in M are larger than -1")
else:
    print("all elements in M are not larger than -1")

all elements in M are larger than -1


## TLDR:
- всегда используйте встроенные в np функции;
- векторизуйте везде, где это возможно!

# 2.5. Numpy - I/O.

В данном случае у нас на выбор 2 опции - либо формат numpy, либо просто текстовый файл.

In [336]:
!ls

Black_man.txt	  HW1.ipynb	    numpy-3.ipynb  pandas.ipynb
frame1234.csv.gz  matplotlib.ipynb  numpy.ipynb


In [337]:
np.save("random12345.npy", M)

In [338]:
!ls

Black_man.txt	  HW1.ipynb	    numpy-3.ipynb  pandas.ipynb
frame1234.csv.gz  matplotlib.ipynb  numpy.ipynb    random12345.npy


In [339]:
!cat Black_man.txt | head -9

Черный человек
Друг мой, друг мой,
Я очень и очень болен.
Сам не знаю, откуда взялась эта боль.
То ли ветер свистит
Над пустым и безлюдным полем,
То ль, как рощу в сентябрь,
Осыпает мозги алкоголь.



In [340]:
N = np.load("random12345.npy")

In [341]:
N

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [342]:
np.savetxt('random_txt.csv', M, delimiter='\t', fmt='%.1e')

In [343]:
! cat random_txt.csv

0.0e+00	1.0e+00	2.0e+00
3.0e+00	4.0e+00	5.0e+00
6.0e+00	7.0e+00	8.0e+00


In [ ]:
np.loadtxt('random_txt.csv')

# А теперь задачки!

#### Написать функцию, которая поможет развернуть все слова в строке:

In [ ]:
%%timeit

In [346]:
s = "Hello world"

In [344]:
def reverse(x):
    return x[::-1].split()

In [347]:
reverse(s)

['dlrow', 'olleH']

#### Написать функцию, которая определяет является ли число палиндромом

In [348]:
x1 = 126567654
x2 = 12345654321

In [349]:
def is_palindrom(x):
    return str(x) == str(x)[::-1]

In [350]:
is_palindrom(x1)

False

In [351]:
is_palindrom(x2)

True

#### Сложите цифры целого числа

In [355]:
a = 126567654

In [361]:
np.array(list(str(a))).astype(int)

array([1, 2, 6, 5, 6, 7, 6, 5, 4])

In [357]:
def summarize(a):
    return np.array(list(str(a))).astype(int).sum()

In [358]:
summarize(a)

42

#### Извлеките из массива числа, делимые на 15.

In [364]:
nums = np.array([45, 55, 60, 37, 100, 105, 220])

In [368]:
nums % 15

array([ 0, 10,  0,  7, 10,  0, 10])

In [365]:
def dev_15(ar):
    return ar[ar % 15 == 0]

In [366]:
dev_15(nums)

array([ 45,  60, 105])

#### Напишите функцию, которая создаёт комбинацию двух списков таким образом:

[1, 2, 3] (+) [11, 22, 33] -> [1, 11, 2, 22, 3, 33]

In [370]:
x = np.array([1, 2, 3, -1])
y = np.array([11, 22, 33, 1123])

array([[ 1],
       [ 2],
       [ 3],
       [-1]])

In [382]:
def union(a, b):
    return np.hstack((a.reshape(-1, 1), b.reshape(-1, 1))).ravel()

In [386]:
def union(a, b):
    res = np.zeros(len(a) + len(b)).astype(int)
    res[::2] = a
    res[1::2] = b
    return res

In [387]:
union(x, y)

array([   1,   11,    2,   22,    3,   33,   -1, 1123])

In [ ]:
union(x, y)

#### Написать функцию, которая удаляет лишние пробелы в строке

In [388]:
x = " I   Love        Python    "

In [389]:
def delete_spaces(string):
    return " ".join(x.split())

In [390]:
delete_spaces(x)

'I Love Python'