<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#1.0.-Pandas---Первое-знакомство" data-toc-modified-id="1.0.-Pandas---Первое-знакомство-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>1.0. Pandas - Первое знакомство</a></span></li><li><span><a href="#НО" data-toc-modified-id="НО-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>НО</a></span></li><li><span><a href="#1.1.-Pandas-DataFrame" data-toc-modified-id="1.1.-Pandas-DataFrame-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>1.1. Pandas DataFrame</a></span></li><li><span><a href="#1.2.-Индексирование." data-toc-modified-id="1.2.-Индексирование.-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>1.2. Индексирование.</a></span></li><li><span><a href="#1.3.-Работа-со-столбцами." data-toc-modified-id="1.3.-Работа-со-столбцами.-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>1.3. Работа со столбцами.</a></span></li><li><span><a href="#1.4.-File-I/O." data-toc-modified-id="1.4.-File-I/O.-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>1.4. File I/O.</a></span></li></ul></div>

# 1.0. Pandas - Первое знакомство

In [2]:
%matplotlib inline
import pandas as pd
import numpy as np

http://pandas.pydata.org/

Pandas - open-source  проект, предоставляющий средства для работы с данными в Питоне с использованием абстракций более высокого уровня, чем numpy.

В основе своей pandas полагается на структуры данных numpy, но вместе с тем предоставляет:

* различные типы данных в рамках одной структуры pandas.DataFrame;
* работу с пропущенными значениями;
* удобную работу с типом DateTime;
* набор методов для совместного использования нескольких массивов данных.

** Series **

Series - это массив размерности один, который может содержать данные различного типа, и 1:1 соответствие между данными и некоторой меткой, присвоенной каждому элементу.

In [3]:
series = pd.Series([-12, np.NaN, 1])

In [4]:
series

0   -12.0
1     NaN
2     1.0
dtype: float64

In [5]:
series.values

array([-12.,  nan,   1.])

In [6]:
series.index

RangeIndex(start=0, stop=3, step=1)

In [26]:
series

0   -12.0
1     NaN
2     1.0
dtype: float64

Мы можем создавать объекты, самостоятельно задавая индекс:

In [7]:
series2 = pd.Series([0, 1, 2], index=['a', 'b', 'c'], name='column')

In [8]:
series2.name

'column'

In [9]:
series2

a    0
b    1
c    2
Name: column, dtype: int64

In [10]:
series2.index

Index(['a', 'b', 'c'], dtype='object')

Преимущества индексирования понятны - мы имеем быстрый доступ к элементам массива, при этом можем пользоваться всеми (практически) свойствами массивов numpy.

In [11]:
series

0   -12.0
1     NaN
2     1.0
dtype: float64

In [12]:
series2

a    0
b    1
c    2
Name: column, dtype: int64

In [13]:
series[0]

-12.0

In [14]:
series2["c"]

2

In [15]:
series[0:2]

0   -12.0
1     NaN
dtype: float64

**Булево индексирование:**

In [16]:
series > 0

0    False
1    False
2     True
dtype: bool

In [17]:
series.values > 0

array([False, False,  True])

In [18]:
series[series > 0]

2    1.0
dtype: float64

In [19]:
1 in series

True

In [23]:
3 in series

False

In [22]:
series

0   -12.0
1     NaN
2     1.0
dtype: float64

Конструктор принимет массив ранга один либо словарь. Ключи словаря используются как индекс (в отсортированном порядке):

In [24]:
pd.Series({'a': 1, 'c': 2, 'b': 3})

a    1
c    2
b    3
dtype: int64

In [26]:
pd.Series({'a': 1, 'c': 2, 'c': 10, 'b': 3, 'c': 12})

a     1
c    12
b     3
dtype: int64

In [27]:
index = ['a_letter', 'b_letter', 'c_letter', 'c']

Если вызывается конструктор со словарем и парметром index = , то отсутствующие в словаре ключи получат NaN.

In [28]:
pd.Series({'a_letter': 1, 'b_letter': 2, 'c': 3}, index=index)

a_letter    1.0
b_letter    2.0
c_letter    NaN
c           3.0
dtype: float64

In [29]:
pd.Series([1, 2, 3], index=index[:3])

a_letter    1
b_letter    2
c_letter    3
dtype: int64

Операции с Series напоминают операции с ndarray:

In [30]:
series

0   -12.0
1     NaN
2     1.0
dtype: float64

In [31]:
series[1] = 100

In [32]:
series

0    -12.0
1    100.0
2      1.0
dtype: float64

In [33]:
series + series

0    -24.0
1    200.0
2      2.0
dtype: float64

In [34]:
series * series

0      144.0
1    10000.0
2        1.0
dtype: float64

In [35]:
np.exp(series.astype(int))

0    6.144212e-06
1    2.688117e+43
2    2.718282e+00
dtype: float64

Самому Series и индексу можно присвоить атрибут имя:

In [36]:
series.name = 'some_test_series'

In [37]:
series

0    -12.0
1    100.0
2      1.0
Name: some_test_series, dtype: float64

In [38]:
series.index.name = 'some_test_index'

In [39]:
series

some_test_index
0    -12.0
1    100.0
2      1.0
Name: some_test_series, dtype: float64

In [40]:
series.index

RangeIndex(start=0, stop=3, step=1, name='some_test_index')

Важно помнить, как pandas обращается с несовпадающими индексами:

In [41]:
a = pd.DataFrame()
a["features"] = [1, 2, 4]

In [42]:
a

features
0         1
1         2
2         4

In [43]:
first_series = pd.Series({'a': 1, 'b': 2, 'c': 2})
second_series = pd.Series({'a': 1, 'b': 3, 'd': -1})

In [44]:
first_series + second_series

a    2.0
b    5.0
c    NaN
d    NaN
dtype: float64

In [45]:
a = first_series / second_series

Индекс всегда можно поменять:

In [46]:
series

some_test_index
0    -12.0
1    100.0
2      1.0
Name: some_test_series, dtype: float64

In [47]:
series.index = ['a_letter', 'b_letter', 'c_letter']

In [48]:
series

a_letter    -12.0
b_letter    100.0
c_letter      1.0
Name: some_test_series, dtype: float64

In [49]:
series.loc['a_letter':"c_letter"]

a_letter    -12.0
b_letter    100.0
c_letter      1.0
Name: some_test_series, dtype: float64

In [52]:
series.iloc[0:2]

a_letter    -12.0
b_letter    100.0
Name: some_test_series, dtype: float64

In [53]:
series.loc['a_letter':'b_letter']

a_letter    -12.0
b_letter    100.0
Name: some_test_series, dtype: float64

In [54]:
series[0:1]

a_letter   -12.0
Name: some_test_series, dtype: float64

In [55]:
series['a_letter'] = 200

In [56]:
series

a_letter    200.0
b_letter    100.0
c_letter      1.0
Name: some_test_series, dtype: float64

# 1.1. Pandas DataFrame

Представим себе структуру, которая могла бы содержать несколько объекто типа Series, объединенных общим индексом. Тогда бы такая структура являлась pandas.DataFrame - табличным форматом данных, снабженным 2 типами индексов - строчным и колоночным.

In [57]:
df = pd.DataFrame({'A': [20, 10, 30], 'B': np.random.randn(3),
                   'C': ['A', 'B', 'C']}, index=['a', 'b', 'c'])

In [58]:
df

A         B  C
a  20  1.576458  A
b  10 -0.801945  B
c  30  0.195569  C

In [59]:
df.values

array([[20, 1.5764584540938962, 'A'],
       [10, -0.8019445980853889, 'B'],
       [30, 0.19556936716709752, 'C']], dtype=object)

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, a to c
Data columns (total 3 columns):
A    3 non-null int64
B    3 non-null float64
C    3 non-null object
dtypes: float64(1), int64(1), object(1)
memory usage: 96.0+ bytes


In [62]:
df

A         B  C
a  20  1.576458  A
b  10 -0.801945  B
c  30  0.195569  C

In [61]:
df.describe()

A         B
count   3.0  3.000000
mean   20.0  0.323361
std    10.0  1.194340
min    10.0 -0.801945
25%    15.0 -0.303188
50%    20.0  0.195569
75%    25.0  0.886014
max    30.0  1.576458

Выбор столбца ничем не отличается от стандартного \_\_getitem\_\_ синтаксиса:

In [63]:
df['A']

a    20
b    10
c    30
Name: A, dtype: int64

In [64]:
df[['A', 'C']]

A  C
a  20  A
b  10  B
c  30  C

In [65]:
df.C

a    A
b    B
c    C
Name: C, dtype: object

Возможные аргументы для конструктора:

* массив ранга 2 (индексы для столбцов и строк передаются отдельным аргументом либо будет использован xrange);
* словарь массивов ранга 1 (ключ - имя стобца, данные - элементы последовательности);
* словарь объектов pd.Series;
* словарь словарей (ключи внутреннего словаря - имена столбцов), ключи внешнего словаря - индекс обеъкта;

Выбор строки:

In [66]:
df.loc[['a', 'b']]

A         B  C
a  20  1.576458  A
b  10 -0.801945  B

--  N: Обратите внимание - slice подобного типа включает в себя крайний объект "справа".

In [67]:
df.loc['a':'b']

A         B  C
a  20  1.576458  A
b  10 -0.801945  B

--  N: А такой - не включает.

In [68]:
df.iloc[0:1]

A         B  C
a  20  1.576458  A

In [69]:
df.loc['a':'b', ['A', 'C']]

A  C
a  20  A
b  10  B

In [70]:
df.iloc[0:2, [0, 2]]

A  C
a  20  A
b  10  B

** Операции с dataframe **

In [71]:
df

A         B  C
a  20  1.576458  A
b  10 -0.801945  B
c  30  0.195569  C

In [72]:
df[['A', 'B']] + 5

A         B
a  25  6.576458
b  15  4.198055
c  35  5.195569

In [73]:
df[['A', 'C']] + df[['A', 'C']]

A   C
a  40  AA
b  20  BB
c  60  CC

Теперь внимание:

In [87]:
df1 = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]}, index=[1, 2, 0])
df2 = pd.DataFrame({'A': [6, 2, 4], 'B': [9, 1, 4]}, index=[2, 0, 1])

In [88]:
df1

A  B
1  1  4
2  2  5
0  3  6

In [89]:
df2

A  B
2  6  9
0  2  1
1  4  4

In [90]:
df1 + df2

A   B
0  5   7
1  5   8
2  8  14

In [86]:
df2 + df1

A   B
0  3   5
1  6   9
2  9  15

In [83]:
df1.values + df2.values

array([[ 7, 13],
       [ 4,  6],
       [ 7, 10]])

In [78]:
df1.values

array([[1, 4],
       [2, 5],
       [3, 6]])

In [79]:
df2.values

array([[6, 9],
       [2, 1],
       [4, 4]])

In [80]:
df1.values + df2.values

array([[ 7, 13],
       [ 4,  6],
       [ 7, 10]])

Очень хорошо!

In [91]:
df3 = pd.DataFrame(np.random.randn(5, 3), columns=['A', 'B', 'C'])
df3

A         B         C
0  0.294203 -0.347678  0.579053
1  0.393419  0.278008 -0.262405
2  0.101989 -0.291965 -0.453333
3 -1.634579  0.225733 -0.850468
4  1.356140 -1.769168 -0.567138

In [92]:
df1

A  B
1  1  4
2  2  5
0  3  6

In [93]:
df1 + df3

A         B   C
0  3.294203  5.652322 NaN
1  1.393419  4.278008 NaN
2  2.101989  4.708035 NaN
3       NaN       NaN NaN
4       NaN       NaN NaN

После примера с Series - такое поведение как раз и ожидалось.

Тем не менее, бывают случаи, когда нам требуется чем - либо заполнить места, в которых индекс не пересекается. В таких случаях удобно использовать параметр fill_value.

In [95]:
df3

A         B         C
0  0.294203 -0.347678  0.579053
1  0.393419  0.278008 -0.262405
2  0.101989 -0.291965 -0.453333
3 -1.634579  0.225733 -0.850468
4  1.356140 -1.769168 -0.567138

In [94]:
df1.add(df3, fill_value=0)

A         B         C
0  3.294203  5.652322  0.579053
1  1.393419  4.278008 -0.262405
2  2.101989  4.708035 -0.453333
3 -1.634579  0.225733 -0.850468
4  1.356140 -1.769168 -0.567138

Таких "гибких" арифметических операций 4:

* df.add;
* df.sub;
* df.div;
* df.mul.

# 1.2. Индексирование.

Для индекса pandas имеет отдельный тип объекта - index object.

In [96]:
s1 = pd.Series(range(3), index=['a', 'b', 'c'])

In [97]:
s1

a    0
b    1
c    2
dtype: int64

In [98]:
index = s1.index

In [99]:
index

Index(['a', 'b', 'c'], dtype='object')

In [100]:
index[0]

'a'

In [101]:
s2 = pd.Series([1.5, -2.5, 0], index=index)

In [102]:
s2.index is s1.index

True

In [103]:
index

Index(['a', 'b', 'c'], dtype='object')

** Реиндексирование **

In [104]:
ser3 = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [105]:
ser3

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [106]:
ser4 = ser3.reindex(['a', 'b', 'c', 'd', 'e'])

In [107]:
ser4

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

Столь же просто менять индекс объекта DataFrame:

In [108]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'], 
                     columns=['Ohio', 'Texas', 'California'])

In [109]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [110]:
frame2 = frame.reindex(index=['a', 'b', 'c', 'd'])

In [111]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [112]:
states = ['Texas', 'Utah', 'California']

In [114]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [113]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [115]:
frame.rename(columns={'Texas': "Moscow"})

Ohio  Moscow  California
a     0       1           2
c     3       4           5
d     6       7           8

# 1.3. Работа со столбцами.

In [116]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'), 
                  index=['F', 'S', 'T', 'R'])

In [117]:
frame

b         d         e
F  0.045256  0.122858  0.561993
S  0.118494  1.793742  0.741002
T  1.562984 -0.277654  0.469613
R  1.943629  0.801746 -0.692070

Как вы уже поняли, никаких проблем с функцией, которая работает в numpy поэлементно, у нас не возникнет:

In [118]:
np.power(frame, 2)

b         d         e
F  0.002048  0.015094  0.315836
S  0.014041  3.217511  0.549084
T  2.442920  0.077092  0.220536
R  3.777693  0.642796  0.478961

Однако, чаще нам нужно применить функцию к какому либо столбцу - например, почитать абсолютное значение, сконвертировать из ts в datetime итд.

In [119]:
frame

b         d         e
F  0.045256  0.122858  0.561993
S  0.118494  1.793742  0.741002
T  1.562984 -0.277654  0.469613
R  1.943629  0.801746 -0.692070

In [120]:
new_format = lambda x: '%.2f' % x

In [121]:
frame.applymap(new_format)

b      d      e
F  0.05   0.12   0.56
S  0.12   1.79   0.74
T  1.56  -0.28   0.47
R  1.94   0.80  -0.69

Для Series метод назывется map().

In [122]:
frame['e'] = frame['e'].map(lambda x: x ** 2) 

In [123]:
frame['e']

F    0.315836
S    0.549084
T    0.220536
R    0.478961
Name: e, dtype: float64

In [124]:
frame['e'] = frame['e'] ** 2

In [125]:
frame["e"]

F    0.099752
S    0.301493
T    0.048636
R    0.229404
Name: e, dtype: float64

In [126]:
frame['e'] = frame['e'].apply(lambda x: x ** 2) 

In [127]:
frame["e"]

F    0.009951
S    0.090898
T    0.002365
R    0.052626
Name: e, dtype: float64

Чтобы получить доступ к списку названий, достаточно обратиться к df.columns:

In [128]:
frame.columns

Index(['b', 'd', 'e'], dtype='object')

Также полезно следующее:

In [129]:
df.dtypes

A      int64
B    float64
C     object
dtype: object

In [130]:
df

A         B  C
a  20  1.576458  A
b  10 -0.801945  B
c  30  0.195569  C

Для сортировки по индексу стоит вызвать df.sort_index(), который возвращает копию исходного объекта:

In [133]:
frame.sort_values("d")

b         d         e
T  1.562984 -0.277654  0.002365
F  0.045256  0.122858  0.009951
R  1.943629  0.801746  0.052626
S  0.118494  1.793742  0.090898

In [131]:
frame.sort_index()

b         d         e
F  0.045256  0.122858  0.009951
R  1.943629  0.801746  0.052626
S  0.118494  1.793742  0.090898
T  1.562984 -0.277654  0.002365

In [117]:
frame.sort_index(axis=1, ascending=False)

e         d         b
F  0.052863 -0.562064 -1.126801
S  0.192427 -1.080367  1.840314
T  1.588210 -1.029383 -1.133131
R  1.281041 -0.120900 -0.048836

Чтобы отсортировать по значению столбцов:

In [134]:
frame.sort_index(by=['d', 'b'])

/data/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: by argument to sort_index is deprecated, please use .sort_values(by=...)
  """Entry point for launching an IPython kernel.


b         d         e
T  1.562984 -0.277654  0.002365
F  0.045256  0.122858  0.009951
R  1.943629  0.801746  0.052626
S  0.118494  1.793742  0.090898

In [135]:
frame.sort_values(by=['d', 'b'])

b         d         e
T  1.562984 -0.277654  0.002365
F  0.045256  0.122858  0.009951
R  1.943629  0.801746  0.052626
S  0.118494  1.793742  0.090898

Также значениям можно присвоить ранг:

In [136]:
frame.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, F to R
Data columns (total 3 columns):
b    4 non-null float64
d    4 non-null float64
e    4 non-null float64
dtypes: float64(3)
memory usage: 288.0+ bytes


In [137]:
frame.describe()

b         d         e
count  4.000000  4.000000  4.000000
mean   0.917591  0.610173  0.038960
std    0.977891  0.906136  0.041089
min    0.045256 -0.277654  0.002365
25%    0.100185  0.022730  0.008054
50%    0.840739  0.462302  0.031288
75%    1.658145  1.049745  0.062194
max    1.943629  1.793742  0.090898

# 1.4. File I/O.

http://pandas.pydata.org/pandas-docs/stable/io.html

Как видно из оффициальной документации (выше), в качестве входного формата могут использоваться следующие:
* read_csv
* read_excel
* read_hdf
* read_sql
* read_json
* read_msgpack (experimental)
* read_html
* read_gbq (experimental)
* read_stata
* read_sas
* read_clipboard
* read_pickle

Каждый из них снабжен "зеркальным" методом "to".

Думаю, что чаще всего вас придется пользоваться методом "read_csv". Подробная сигнатура:

In [138]:
pd.read_*?

In [ ]:
pd.read_csv?

In [ ]:
pd.read_excel()

In [139]:
frame

b         d         e
F  0.045256  0.122858  0.009951
S  0.118494  1.793742  0.090898
T  1.562984 -0.277654  0.002365
R  1.943629  0.801746  0.052626

In [143]:
frame[["b", "d", "e"]].to_csv("frame1234.csv.gz", sep="\t", encoding="utf-8", compression="gzip", index=False)

In [144]:
frame = pd.read_csv("frame1234.csv.gz", sep="\t")

In [145]:
frame

b         d         e
0  0.045256  0.122858  0.009951
1  0.118494  1.793742  0.090898
2  1.562984 -0.277654  0.002365
3  1.943629  0.801746  0.052626

In [ ]:
!ls

In [136]:
!zcat frame1234.csv.gz

	b	d	e
0	-1.1268009509503607	-0.5620644379815282	0.05286259575121775
1	1.8403139362459813	-1.0803670408692791	0.19242670383992366
2	-1.133130951505931	-1.0293830878819683	1.5882098256125448
3	-0.0488361033251371	-0.12090035166412905	1.2810413243879384


In [137]:
frame.head(1)

Unnamed: 0         b         d         e
0           0 -1.126801 -0.562064  0.052863

In [138]:
frame.columns

Index(['Unnamed: 0', 'b', 'd', 'e'], dtype='object')

In [139]:
frame

Unnamed: 0         b         d         e
0           0 -1.126801 -0.562064  0.052863
1           1  1.840314 -1.080367  0.192427
2           2 -1.133131 -1.029383  1.588210
3           3 -0.048836 -0.120900  1.281041

In [140]:
frame.get_dtype_counts()

/data/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: `get_dtype_counts` has been deprecated and will be removed in a future version. For DataFrames use `.dtypes.value_counts()
  """Entry point for launching an IPython kernel.


float64    3
int64      1
dtype: int64

In [141]:
frame["b"].value_counts()

-1.126801    1
-0.048836    1
 1.840314    1
-1.133131    1
Name: b, dtype: int64

In [ ]:
frame.values